mohbeli/Models/Items.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace mohbeli.Models
{
    public class Items
    {
        public int Id { get; set; }

        public string ProductName { get; set; }

        public string Code { get; set; }

        public int Price { get; set; }

        public int Quantity { get; set; }

        public int ItemIndex { get; set; }
    }
}

mohbeli/Models/MohBeliDetail.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using mohbeli.Models;

namespace mohbeli.Models
{
    public class MohBeliDetail
    {
        public int Id { get; set; }

        public string CustomerName { get; set; }

        public string MobileNumber { get; set; }

        public string Address { get; set; }

        public int TotalAmount { get; set; }

        public int TaxAmount { get; set; }

        public int NetAmount { get; set; }

        public List<Items> Items { get; set; }

        public MohBeliDetail()
        {
            Items = new List<Items>();
        }
    }
}

mohbeli/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mohbeli.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

mohbeli/Controllers/MohBeliController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using mohbeli.Models;
using mohbeli.Repository;

namespace mohbeli.Controllers
{
    public class MohBeliController : Controller
    {
        // GET: mohbeli
        public ActionResult Index()
        {
            Data data = new Data();
            var list = data.GetAllDetail();
            return View(list);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(MohBeliDetail details)
        {
            Data data = new Data();
            data.SaveMohBeliDetails(details);
            ModelState.Clear();
            return View();
        }

        public ActionResult CreateItem(Items item)
        {
            return PartialView("_CreateItem",item);
        }

        public ActionResult ViewMohBeli(int Id)
        {
            Data data = new Data();
            var details = data.GetDetail(Id);
            return View(details);
        }
    }
}

mohbeli/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}

<div class="container shadow mt-4 rounded">
    <div class="row">
        <div class="col-sm-12 col-md-12 col-lg-12">
            <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img src="~/Content/Images/Data-Processing-Services.jpg" class="d-block w-100" style="height:300px" />
                    </div>
                    <div class="carousel-item">
                        <img src="~/Content/Images/datarow.jpg" class="d-block w-100" style="height:300px" />
                    </div>
                    <div class="carousel-item">
                        <img src="~/Content/Images/datareceipt.jpg" class="d-block w-100" style="height:300px" />
                    </div>
                </div>
            </div>
            <div class="mt-3 mb-3">
                <h2>MohBeli Application</h2>
            </div>
        </div>
    </div>
</div>

mohbeli/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body class="pt-8">
    <nav class="navbar navbar-expand-lg navbar-light bg-light shadow sticky-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">MohBeli</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    @Html.ActionLink("Home", "Index", "Home", null, new { @class = "nav-link active" })
                    @Html.ActionLink("View MohBeli", "Index", "MohBeli", null, new { @class = "nav-link active" })
                    @Html.ActionLink("Create MohBeli", "Create", "MohBeli", null, new { @class = "nav-link active" })
                </div>
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

mohbeli/Views/mohbeli/Create.cshtml
@model mohbeli.Models.MohBeliDetail
@{
    ViewBag.Title = "Create";
}

<div class="container mt-4">
    <div class="row">
        <div class="col-sm-6 col-md-6 col-lg-6 offset-3 shadow rounded">
            @using (Html.BeginForm())
            {
                <div>
                    <h3 class="text-center">Create MohBeli</h3>
                </div>
                <div class="mb-3">
                    <label class="form-label">Customer Name</label>
                    @Html.TextBoxFor(modelItem => modelItem.CustomerName, new { @class = "form-control form-control-sm" })
                </div>
                <div class="mb-3">
                    <label class="form-label">Mobile Number</label>
                    @Html.TextBoxFor(modelItem => modelItem.MobileNumber, new { @class = "form-control form-control-sm" })
                </div>
                <div class="mb-3">
                    <label class="form-label">Address</label>
                    @Html.TextBoxFor(modelItem => modelItem.Address, new { @class = "form-control form-control-sm" })
                </div>
                <div class="mb-3">
                    <div class="mb-2">
                        <span class="h5">Items</span>
                        <button type="button" class="btn btn-sm btn-primary border float-end" data-bs-toggle="modal" data-bs-target="#modalbox">Add</button>
                    </div>
                    <table id="items" class="table table-striped table-responsive table-hover table-bordered">
                        <thead>
                            <tr>
                                <th>Product Name</th>
                                <th>Code</th>
                                <th>Price</th>
                                <th>Quantity</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>

                        </tbody>
                    </table>
                </div>
                <div class="mb-3">
                    <button type="submit" class="btn btn-sm btn-success">Save</button>
                </div>
            }
        </div>
    </div>
</div>
<div class="modal fade" id="modalbox" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body">
                <div class="mb-3">
                    <label class="form-label">Product Name</label>
                    <input type="text" class="form-control form-control-sm" placeholder="Enter Product Name" id="productname" />
                </div>
                <div class="mb-3">
                    <label class="form-label">Code</label>
                    <input type="text" class="form-control form-control-sm" placeholder="Enter Code" id="code" />
                </div>
                <div class="mb-3">
                    <label class="form-label">Price</label>
                    <input type="text" class="form-control form-control-sm" placeholder="Enter Price" id="price" />
                </div>
                <div class="mb-3">
                    <label class="form-label">Quantity</label>
                    <input type="text" class="form-control form-control-sm" placeholder="Enter Quantity" id="quantity" />
                </div>
                <div class="mb-3">
                    <button class="btn btn-sm btn-success" type="button" id="addItem">Add</button>
                    <button class="btn btn-sm btn-primary" type="button" data-bs-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $('#addItem').click(function () {
            let productName = $('#productname').val();
            let code = $('#code').val();
            let price = $('#price').val();
            let quantity = $('#quantity').val();
            let ItemIndex = $('#items tbody tr').length;
            $.ajax({
                url: "/mohbeli/CreateItem",
                type: "POST",
                data: { productName, code, price, quantity, ItemIndex },
                success: function (resp) {
                    $('#items tbody').append(resp);
                    $('#productname').val("");
                    $('#code').val("");
                    $('#price').val("");
                    $('#quantity').val("");
                },
                error: function (err) {
                    alert(err)
                }
            })
        })
    })
</script>

mohbeli/Views/mohbeli/Index.cshtml
@model IEnumerable<mohbeli.Models.MohBeliDetail>
@{
    ViewBag.Title = "mohbeli";
}

<div class="container shadow rounded mt-4">
    <div class="row">
        <div class="col-12">
            <h4>All MohBeli</h4>
            <table class="table table-responsive table-striped table-hover table-bordered text-center">
                <thead>
                    <tr>
                        <th>Order No.</th>
                        <th>Customer Name</th>
                        <th>Mobile Number</th>
                        <th>Address</th>
                        <th>Total Amount</th>
                        <th>Tax Amount</th>
                        <th>Net Amount</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                    <tr>
                        <td>@item.Id</td>
                        <td>@item.CustomerName</td>
                        <td>@item.MobileNumber</td>
                        <td>@item.Address</td>
                        <td>@item.TotalAmount</td>
                        <td>@item.TaxAmount</td>
                        <td>@item.NetAmount</td>
                        <td>
                            @Html.ActionLink("View", "ViewMohBeli", "MohBeli", new { Id = @item.Id }, new { @class = "btn btn-sm btn-light border" })
                        </td>
                    </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

mohbeli/Views/mohbeli/ViewMohBeli.cshtml
@model mohbeli.Models.MohBeliDetail
@{
    ViewBag.Title = "ViewMohBeli";
}

<div class="container shadow rounded mt-4">
    <div class="row">
        @*<div class="col-6">
                        <h3 class="text-primary">Programming With Afiq</h3>
                        <pre>
            Temerloh, Pahang
            Phone : 01174760196
            Gmail : ahmadafiqahnaf@gmail.com
            </pre>
                    </div>*@
        @*<div class="offset-3 col-3">
                        <h3 class="text-primary">MohBeli</h3>
                        <pre>
            Order No. : @Model.Id
            </pre>
                    </div>*@
    </div>
    <div class="row mt-3">
        <div class="col-3">
            <h4 class="bg-primary text-white">MohBeli</h4>
            <pre>
Customer Name : @Model.CustomerName
Mobile No. : @Model.MobileNumber
Address : @Model.Address
</pre>
        </div>
        <div class="col-3">
            <pre>
Order No. : @Model.Id
</pre>
        </div>
    </div>
    <div class="row mt-3">
        <div class="col-12">
            <table class="table table-bordered table-striped table-responsive">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Product Name</th>
                        <th>Code</th>
                        <th>Price</th>
                        <th>Quantity</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Items)
                    {
                        <tr>
                            <td>@item.Id</td>
                            <td>@item.ProductName</td>
                            <td>@item.Code</td>
                            <td>@item.Price</td>
                            <td>@item.Quantity</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="row mt-2">
        <div class="col-12">
            <h4 class="float-end">Total Amount : @Model.TotalAmount</h4>
        </div>
    </div>
    <div class="row mt-2">
        <div class="col-12">
            <h5 class="float-end">Tax Amount : @Model.TaxAmount</h5>
        </div>
    </div>
    <div class="row mt-2">
        <div class="col-12">
            <h5 class="float-end">Net Amount : @Model.NetAmount</h5>
        </div>
    </div>
</div>

mohbeli/Views/mohbeli/_CreateItem.cshtml
@model mohbeli.Models.Items

<tr id="@Model.ItemIndex">
    <td>
        @Model.ProductName
        <input type="hidden" name="Items[@Model.ItemIndex].ProductName" value="@Model.ProductName" />
    </td>
    <td>
        @Model.Code
        <input type="hidden" name="Items[@Model.ItemIndex].Code" value="@Model.Code" />
    </td>
    <td>
        @Model.Price
        <input type="hidden" name="Items[@Model.ItemIndex].Price" value="@Model.Price" />
    </td>
    <td>
        @Model.Quantity
        <input type="hidden" name="Items[@Model.ItemIndex].Quantity" value="@Model.Quantity" />
    </td>
    <td><button name="X-HTTP-Method-Override" value="DELETE" formnovalidate 
               class="btn btn-sm bg-danger text-white" onclick="return confirm('Are you sure?')">Delete</button></td>
</tr>